id: PBDFCC7E3
initial_creation_type: ocr
source_metadata:
  volumes:
    e224264b48d14e759afa81e5aed2c1e7:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: རྡོ་རྗེ་ཕག་མོ་སྒྲོལ་མ་ལ་བསྟོད་པ།
      total_pages: 1856
      volume_number: 14
